### ISSUE TITLE
Can't install due to mdreizin/webpack-config#8

### ISSUE THREAD

**Issue by pheuter** [mdreizin/webpack-config-stream#19]
mdreizin/webpack-config#8

```
npm ERR! notarget No compatible version found: webpack-config@'>=0.7.0 <0.8.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.8.1"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'gulp-webpack-build'
npm ERR! notarget
```

**Comment by basketofsoftkittens** [comment]
+1.

**Comment by basketofsoftkittens** [comment]
@pheuter upgrading to 13.1 should fix it. though the tag is not visible on github. is the 13.1 tag pushed remote @mdreizin ?

**Comment by mdreizin** [comment]
@basketofsoftkittens @pheuter I'm sorry guys it was my fault. I have accidentally run `npm unpublish .` instead of `npm unpublish` for `webpack-config` and now you have got this issue. Please update to `0.12.2`.

**Comment by mdreizin** [comment]
@basketofsoftkittens @pheuter I'm going to close it and I would like to know everything is ok?

**Comment by pheuter** [comment]
@mdreizin yeah, seems to be fixed now with the latest version, would of been nice if `npm` provided a confirmation when unpublushing packages ;)
